#!/usr/bin/env python3
"""Generates Revdex/Models/CarCatalog.swift from the tables in scripts/catalog.

Dex numbers are permanent. A saved catch, a database row and a shared card all
store the car by id, so every (make, model) that has ever been issued a number
keeps it forever. The registry lives in scripts/dex_ids.json; new cars are
appended after the highest number ever used and written back to it.

Run: python3 scripts/gen_catalog.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from catalog import ALL  # noqa: E402

REGISTRY = ROOT / "scripts" / "dex_ids.json"
OUT = ROOT / "Revdex" / "Models" / "CarCatalog.swift"

# Swift type checks a literal array in one go, so the catalog is emitted as
# blocks of this many and concatenated. One 900 element literal makes the
# compiler crawl; a stack of small ones does not.
BLOCK = 50


def key(make, model):
    return f"{make.lower()}|{model.lower()}"


def assign_ids(registry):
    """Frozen number for anything already issued one, next free number for the
    rest, in a stable order so two runs of the same table agree."""
    next_id = max(registry.values(), default=0) + 1
    rows, added = [], []

    for make in sorted(ALL):
        for car in ALL[make]:
            k = key(make, car["model"])
            if k in registry:
                dex = registry[k]
            else:
                dex = next_id
                next_id += 1
                registry[k] = dex
                added.append(f"{make} {car['model']}")
            rows.append((dex, make, car))

    return rows, added


def swift(rows):
    """Rows already carry their permanent id, so they are emitted in dex order
    and the file reads like the dex itself."""
    blocks, lines = [], []
    ordered = sorted(rows, key=lambda r: r[0])

    for start in range(0, len(ordered), BLOCK):
        chunk = ordered[start:start + BLOCK]
        name = f"block{start // BLOCK:02d}"
        blocks.append(name)
        lines.append(f"    private static let {name}: [CarModel] = [")
        for dex, make, c in chunk:
            lines.append(
                f'        CarModel(id: {dex}, make: "{make}", model: "{c["model"]}", '
                f'year: "{c["year"]}", rarity: .{c["rarity"]}, body: .{c["body"]}, '
                f'tint: 0x{c["tint"]:06X}, series: "{c["series"]}", '
                f'production: "{c["production"]}", engine: "{c["engine"]}", '
                f'power: {c["power"]}, torque: {c["torque"]}, drive: .{c["drive"]}, '
                f'gearbox: "{c["gearbox"]}", sprint: {c["sprint"]}, '
                f'topSpeed: {c["top_speed"]}, weight: {c["weight"]}, '
                f'seats: {c["seats"]}, msrp: {c["msrp"]}, fuel: .{c["fuel"]}),'
            )
        lines[-1] = lines[-1].rstrip(",")
        lines.append("    ]")
        lines.append("")

    joined = "\n".join(lines).rstrip()
    total = " + ".join(blocks)
    return joined, total


def main():
    registry = json.loads(REGISTRY.read_text()) if REGISTRY.exists() else {}
    before = len(registry)

    rows, added = assign_ids(registry)

    seen = {}
    for dex, make, car in rows:
        if dex in seen:
            raise SystemExit(f"dex {dex} claimed twice: {seen[dex]} and {make} {car['model']}")
        seen[dex] = f"{make} {car['model']}"

    body, total = swift(rows)
    makes = len({make for _, make, _ in rows})

    text = f"""import SwiftUI

// Generated by scripts/gen_catalog.py. Edit the tables in scripts/catalog,
// never this file.
//
// {len(rows)} cars across {makes} makes, every one carrying its full spec: the
// generation or chassis code, the production run, the engine as it was badged,
// power and torque, drivetrain, gearbox, 0-60, top speed, curb weight, seats
// and the price it wore when new.
//
// Dex numbers are permanent and come from scripts/dex_ids.json, because a saved
// catch stores its car by id. Numbers are never reused or renumbered.

extension Catalog {{
    static let allCars: [CarModel] = {total}

{body}
}}
"""
    OUT.write_text(text)
    REGISTRY.write_text(json.dumps(registry, indent=0, sort_keys=True))

    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} cars, {makes} makes, "
          f"{len(body.splitlines())} lines")
    print(f"registry {before} -> {len(registry)} ({len(added)} new dex numbers)")
    if added:
        print("  " + ", ".join(added[:8]) + (" ..." if len(added) > 8 else ""))

    retired = sorted(set(registry) - {key(m, c["model"]) for _, m, c in rows})
    if retired:
        print(f"WARNING: {len(retired)} numbered cars are missing from the tables, "
              f"so their saved catches would fall back to the first entry:")
        for r in retired:
            print(f"  {r}")


if __name__ == "__main__":
    main()
